language: clojure
jdk:
- openjdk8
services:
- docker
sudo: required
before_install:
- sudo apt-get update
- sudo apt-get install gdal-bin libgdal-dev libgdal-java libgdal20 python-gdal -y
- lein deps 
- lein test
after_success:
- "./bin/build"
