language: clojure
jdk:
- openjdk8
services:
- docker
sudo: required
env:
- LD_LIBRARY_PATH=/usr/lib/jni C_INCLUDE_DIR=/usr/include/gdal
before_install:
- sudo apt-get update
- sudo apt-get install gdal-bin libgdal-dev libgdal-java python-gdal -y
- lein deps 
- lein test
after_success:
- "./bin/build"
