version: "3"

services:

  datahost:
    build: .
    network_mode: "host"
    ports:
      - "8899:8899"

  gaia:
    build: ../.
    network_mode: "host"
    ports:
      - "9876:9876"
    environment:
      - NEMO_HOST=http://localhost:8899
      - SEGMENTS_PATH=/segments
      - PREDICTIONS_PATH=/predictions
      - HTTP_PORT=9876


# s3 server for storage interaction testing
# https://hub.docker.com/r/scality/s3server/
